sudo: false
dist: trusty
language: rust
rust:
  - nightly
  - stable
matrix:
  allow_failures:
    - rust: stable


# Dependencies of kcov, used by coverage
addons:
  apt:
    packages: 
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources: 
      - kalakris-cmake

cache: cargo

before_install:
- nvm install node

install:
- cd web/client
- npm install
- cd ../..

before_script:
  # Install tools if not already installed
  - cargo install --list | grep clippy || cargo install clippy || true # clippy really loves to break, so it's okay if it fails
  - cargo install --list | grep rustfmt || cargo install rustfmt
  - cargo install --list | grep cargo-update || cargo install cargo-update
  - cargo install --list | grep tarpaulin || cargo install cargo-tarpaulin

  # Update all tools
  - cargo install-update -a || true # sometimes nightly breaks stuff, that's okay


  # Lint
  - cd core
  - cargo fmt -- --write-mode=diff
  - cd ..

script:
- cd core
- cargo build --verbose
- cargo test --verbose
- cd ..

- cd web/client
- npm run build
- cd ../..

after_success:
  - cd core
  - cargo clippy -- -Z no-trans -D clippy # clippy really loves to break, so it's okay if it fails
  - cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
