sudo: false
dist: trusty
language: rust
rust:
  - nightly
  - stable
matrix:
  allow_failures:
    - rust: stable


# Dependencies of kcov, used by coverage
addons:
  apt:
    packages:
      - kcov

cache: cargo

before_script:
  # Install tools if not already installed
  - cargo install --list | grep clippy || cargo install clippy
  - cargo install --list | grep rustfmt || cargo install rustfmt
  - cargo install --list | grep cargo-update || cargo install cargo-update
  # Update all tools
  - cargo install-update -a || true # sometimes nightly breaks stuff, that's okay
  # Lint
  - cd core
  - cargo fmt -- --write-mode=diff
  - cargo clippy -- -Z no-trans -D clippy 


after_success:
  - cd ..
  - kcov --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo,/usr/lib --verify target/cov target/debug/shootr-*
