sudo: false
dist: trusty
language: rust
rust:
  - nightly
  - stable
matrix:
  allow_failures:
    - rust: stable


# Dependencies of kcov, used by coverage
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev

cache: cargo

before_script:
  # Install tools if not already installed
  - cargo install --list | grep clippy || cargo install clippy
  - cargo install --list | grep rustfmt || cargo install rustfmt
  - cargo install --list | grep cargo-update || cargo install cargo-update
  # Update all tools
  - cargo install-update -a || true # sometimes nightly breaks stuff, that's okay
  # Lint
  - cd core
  - cargo fmt -- --write-mode=diff
  - cargo clippy -- -Z no-trans -D clippy 


after_success:
  - cd ..
  - wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
    tar xzf master.tar.gz &&
    cd kcov-master &&
    mkdir build &&
    cd build &&
    cmake .. &&
    make &&
    sudo make install &&  
    cd ../.. &&
    rm -rf kcov-master &&
    kcov --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo,/usr/lib --verify target/cov target/debug/shootr-*
