sudo: false
dist: trusty
language: rust
rust:
  - nightly
  - stable
matrix:
  allow_failures:
    - rust: nightly


addons:
  apt:
    packages:
      - openssl
      - libcurl4-openssl-dev

cache: cargo

before_script:
  - cargo install --list | grep cargo-update || cargo install cargo-update
  - cargo install-update -a
  - cargo install --list | grep clippy || cargo install clippy
  - cargo install --list | grep rustfmt || cargo install rustfmt
  - cd core
