[package]
authors = ["Jan Nils Ferner <jn_ferner@hotmail.de>"]
name = "shootr-derive"
version = "0.1.0"

[lib]
proc-macro = true

[dependencies]
quote = "0.3"
syn = "0.11"
specs = "0.9"
derive_more = "0.6.0"
